
# configs/data_split.yaml

split_name: marta_slide_split_v1
output_dir: /scratch/jsanchoz/MARTA/experiments/data_splits/marta_slide_split_v1

strategy: manual_groups
random_seed: 42

group_definition: slide_id
group_key: slide_id

notes: >
  Official slide-level split for main paper experiments.
  Chosen to reduce leakage across ROIs from related slides/images.

manual_split:
  train_groups: ["IM6", "IM9", "IM133"]
  val_groups: ["IM1315"]
  test_groups: ["IM1313", "IM1314"]