# configs/data_split.yaml

split_name: "marta_split_v1"
output_dir: "/scratch/jsanchoz/MARTA/experiments/data_splits/marta_split_v1"

random_seed: 42
strategy: "manual_groups"   # roi_stratified | grouped | manual_groups

# Metadata only
group_definition: "slide"
group_key: "slide_id"
notes: "Official slide-wise MARTA split used for hyperparameter tuning and final model evaluation."

# Only used for roi_stratified / grouped
test_size: 0.15
val_size_within_trainval: 0.15

# Official manual split
manual_split:
  train_groups: ["IM6", "IM9", "IM133"]
  val_groups: ["IM1315"]
  test_groups: ["IM1313", "IM1314"]